@startuml
!define RECTANGLE class

' Definindo os pacotes
package "cliente" {
    RECTANGLE Cliente {
        - nome: String
        - notificacoes: List<String>
        + getNome(): String
        + getNotificacoes(): List<String>
        + adicionarPedido(pedido: Pedido): void
        + update(pedido: Pedido, mensagem: String): void
    }
}

package "pedido" {
    RECTANGLE Pedido {
        - id: String
        - estado: PedidoEstado
        - cliente: Cliente
        + getId(): String
        + getEstado(): PedidoEstado
        + getCliente(): Cliente
        + setEstado(novoEstado: PedidoEstado): void
        + notifyObserver(): void
    }
    
    interface PedidoEstado {
        + getNomeEstado(): String
    }
    
    RECTANGLE PedidoEstadoCriado {
        + getNomeEstado(): String
    }
    
    RECTANGLE PedidoEstadoEmPreparacao {
        + getNomeEstado(): String
    }
    
    RECTANGLE PedidoEstadoEmRota {
        + getNomeEstado(): String
    }
    
    RECTANGLE PedidoEstadoEntregue {
        + getNomeEstado(): String
    }
}

package "factory" {
    RECTANGLE PedidoFactory {
        + criarPedido(cliente: Cliente): Pedido
    }
}

package "main" {
    RECTANGLE Main {
        + main(String[] args): void
    }
}

' Relacionamentos
Cliente -- "0..*" Pedido : tem >
Pedido o-- PedidoEstado : tem >
PedidoEstado <|-- PedidoEstadoCriado
PedidoEstado <|-- PedidoEstadoEmPreparacao
PedidoEstado <|-- PedidoEstadoEmRota
PedidoEstado <|-- PedidoEstadoEntregue
PedidoFactory --> Pedido : cria >
Main --> PedidoFactory : usa >
Cliente --> Pedido : notifica >

@enduml
